// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  heading_and_text: dynamic(() => import("./HeadingAndText")),
  hero: dynamic(() => import("./Hero")),
  slider: dynamic(() => import("./Slider")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  video: dynamic(() => import("./Video")),
};
