// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cards: dynamic(() => import("./Cards")),
  heading_and_text: dynamic(() => import("./HeadingAndText")),
  hero: dynamic(() => import("./Hero")),
  shop: dynamic(() => import("./Shop")),
  slider: dynamic(() => import("./Slider")),
  text_with_image: dynamic(() => import("./TwoColumns")),
  video: dynamic(() => import("./Video")),
};
